version: '3.7'
services:

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: bookstore
    container_name: bookstore
    restart: on-failure
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - bookstore
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - bookstore

networks:
  bookstore:
    driver: bridge
