version: '3.4'
services:

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: bookstore
    container_name: bookstore
    ports:
      - "8080"
    networks:
      - bookstore
    depends_on:
      - "mysql"

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - bookstore

networks:
  bookstore:
    driver: bridge
